/**
 * Produto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.9.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface E021mot { 
    /**
     * Código do motivo da observação ou situação
     */
    codMot?: number;
    /**
     * 
     */
    usualt?: string;
    /**
     * 
     */
    dthger?: Date;
    /**
     * Descrição do motivo da observação ou situação
     */
    desMot?: string;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    usuger?: string;
}
