/**
 * Produto
 * Serviço de Produto do ERPX
 *
 * OpenAPI spec version: 1.10.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E070emp } from './e070emp';
import { EnumTipNtg } from './enumTipNtg';


export interface E047ntg { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * Natureza de Gasto
     */
    codNtg?: number;
    /**
     * 
     */
    dthger?: Date;
    /**
     * Descrição
     */
    desNtg?: string;
    e070emp?: E070emp;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    tipNtg?: EnumTipNtg;
    /**
     * 
     */
    usuger?: string;
}
