/**
 * Produto
 * Serviço de Produto do ERPX
 *
 * OpenAPI spec version: 1.10.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface E070emp { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Nome fantasia da empresa
     */
    sigEmp?: string;
    /**
     * 
     */
    dthger?: Date;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * Código da empresa
     */
    codEmp?: number;
    /**
     * 
     */
    id?: string;
    /**
     * Nome da empresa
     */
    nomEmp?: string;
    /**
     * 
     */
    usuger?: string;
}
