/**
 * Produto
 * Serviço de Produto do ERPX
 *
 * OpenAPI spec version: 1.10.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E012fam } from './e012fam';
import { E021mot } from './e021mot';
import { E047ntg } from './e047ntg';
import { E070emp } from './e070emp';
import { EnumProEpe } from './enumProEpe';
import { EnumSitReg } from './enumSitReg';


export interface E075der { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Código de barras
     */
    codBar?: string;
    /**
     * Código barras livre
     */
    codBa2?: string;
    /**
     * Código da Referência
     */
    codRef?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * Derivação
     */
    codDer?: string;
    /**
     * Descrição complementar
     */
    desCpl?: string;
    /**
     * Peso bruto
     */
    pesBru?: number;
    /**
     * 
     */
    dthger?: Date;
    e047ntg?: E047ntg;
    sitDer?: EnumSitReg;
    /**
     * 
     */
    dthalt?: Date;
    e012fam?: E012fam;
    /**
     * 
     */
    usuger?: string;
    /**
     * Gtin uni. trib
     */
    codGtn?: string;
    /**
     * Peso líquido
     */
    pesLiq?: number;
    proEpe?: EnumProEpe;
    /**
     * Descrição
     */
    desDer?: string;
    e070emp?: E070emp;
    /**
     * 
     */
    id?: string;
    /**
     * Identificação produto
     */
    idePro?: string;
    e021mot?: E021mot;
}
