/**
 * Produto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.9.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnumSitReg } from './enumSitReg';


export interface E076mar { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Nome da marca
     */
    nomMar?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * 
     */
    dthger?: Date;
    /**
     * 
     */
    dthalt?: Date;
    sitMar?: EnumSitReg;
    /**
     * 
     */
    id?: string;
    /**
     * Código da marca/etiqueta vinculada a um produto ou a um pedido
     */
    codMar?: string;
    /**
     * 
     */
    usuger?: string;
}
