/**
 * Produto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.9.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E070emp } from './e070emp';
import { EnumTipPro } from './enumTipPro';


export interface E083ori { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * Código da origem do produto
     */
    codOri?: string;
    /**
     * 
     */
    dthger?: Date;
    e070emp?: E070emp;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * Descrição da origem do produto
     */
    desOri?: string;
    tipPro?: EnumTipPro;
    /**
     * 
     */
    usuger?: string;
}
