/**
 * Produto
 * Serviço de Produto do ERPX
 *
 * OpenAPI spec version: 1.9.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E070emp } from './e070emp';
import { E084cma } from './e084cma';
import { EnumPrpMas } from './enumPrpMas';
import { EnumSitReg } from './enumSitReg';
import { EnumTipMas } from './enumTipMas';


export interface E084mas { 
    /**
     * Valor incremental
     */
    vlrInc?: number;
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * Descrição
     */
    desMas?: string;
    /**
     * 
     */
    dthger?: Date;
    prpMas?: EnumPrpMas;
    tipMas?: EnumTipMas;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * Abreviatura
     */
    abrMas?: string;
    /**
     * 
     */
    usuger?: string;
    /**
     * Último código gerado
     */
    ultCod?: string;
    /**
     * Máscara livre
     */
    masLiv?: boolean;
    /**
     * Quantidade de posições
     */
    qtdPos?: number;
    e070emp?: E070emp;
    /**
     * 
     */
    id?: string;
    sitMas?: EnumSitReg;
    /**
     * Cadastros - componentes de máscaras
     */
    e084cma?: Array<E084cma>;
    /**
     * Código da máscara
     */
    codMas?: string;
}
