/**
 * Produto
 * Serviço de Produto do ERPX
 *
 * OpenAPI spec version: 1.9.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E084mas } from './e084mas';
import { EnumSitReg } from './enumSitReg';


export interface E084cma { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    sitCma?: EnumSitReg;
    e084mas?: E084mas;
    /**
     * 
     */
    dthger?: Date;
    /**
     * Código do componente da máscara
     */
    codCma?: string;
    /**
     * Sequência
     */
    seqCma?: number;
    /**
     * Abreviatura
     */
    abrCma?: string;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * Descrição
     */
    desCma?: string;
    /**
     * 
     */
    usuger?: string;
}
