/**
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E001pes } from './e001pes';
import { EnumSitReg } from './enumSitReg';


export interface E095pes { 
    /**
     * 
     */
    usualt?: string;
    sitFor: EnumSitReg;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * 
     */
    dthger?: Date;
    e001pes?: E001pes;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    usuger?: string;
}
