/**
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumPrpMas = 'V1' | 'V2' | 'V3' | 'V99';

export const EnumPrpMas = {
    V1: 'V1' as EnumPrpMas,
    V2: 'V2' as EnumPrpMas,
    V3: 'V3' as EnumPrpMas,
    V99: 'V99' as EnumPrpMas
};
