/**
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumTipNtg = 'VN' | 'VT' | 'VR';

export const EnumTipNtg = {
    VN: 'VN' as EnumTipNtg,
    VT: 'VT' as EnumTipNtg,
    VR: 'VR' as EnumTipNtg
};
