/**
 * Produto
 * Serviço de Produto do ERPX
 *
 * OpenAPI spec version: 1.9.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumProEpe = 'V0' | 'V1' | 'V2' | 'V3' | 'V4' | 'V5' | 'V9';

export const EnumProEpe = {
    V0: 'V0' as EnumProEpe,
    V1: 'V1' as EnumProEpe,
    V2: 'V2' as EnumProEpe,
    V3: 'V3' as EnumProEpe,
    V4: 'V4' as EnumProEpe,
    V5: 'V5' as EnumProEpe,
    V9: 'V9' as EnumProEpe
};
