/**
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumTipMer = 'VI' | 'VE';

export const EnumTipMer = {
    VI: 'VI' as EnumTipMer,
    VE: 'VE' as EnumTipMer
};
