/**
 * Produto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.9.4
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumTipPro = 'VP' | 'VC' | 'VS';

export const EnumTipPro = {
    VP: 'VP' as EnumTipPro,
    VC: 'VC' as EnumTipPro,
    VS: 'VS' as EnumTipPro
};
