/**
 * Produto
 * Serviço de Produto do ERPX
 *
 * OpenAPI spec version: 1.9.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumSitReg = 'VA' | 'VI';

export const EnumSitReg = {
    VA: 'VA' as EnumSitReg,
    VI: 'VI' as EnumSitReg
};
