/**
 * Produto
 * Serviço de Produto do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E001pes } from './e001pes';


export interface Equipment { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Código do equipamento
     */
    code: string;
    /**
     * 
     */
    dthger?: Date;
    person: E001pes;
    /**
     * Descrição do equipamento
     */
    description: string;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    usuger?: string;
}
