/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E001pes } from './e001pes';
import { E006pai } from './e006pai';
import { E007ufs } from './e007ufs';
import { E008cep } from './e008cep';
import { E008rai } from './e008rai';
import { EnumIndOba } from './enumIndOba';
import { EnumJurFis } from './enumJurFis';
import { EnumSitReg } from './enumSitReg';
import { EnumTipEnd } from './enumTipEnd';


export interface E001end { 
    /**
     * 
     */
    usualt?: string;
    /**
     * 
     */
    dthger?: Date;
    /**
     * CNPJ/CPF
     */
    cnpCpf?: string;
    e008cep?: E008cep;
    /**
     * Telefone
     */
    fonRes?: string;
    /**
     * Celular
     */
    celRes?: string;
    e001pes?: E001pes;
    tipLoc?: EnumTipEnd;
    /**
     * Inscrição estadual
     */
    insEst?: string;
    /**
     * Endereço
     */
    endPes?: string;
    /**
     * Número de inscrição do cadastro nacional de obra (CNO)
     */
    nroCno?: string;
    /**
     * Ponto de referência
     */
    prxEnd?: string;
    /**
     * 
     */
    id?: string;
    /**
     * Fax
     */
    faxRes?: string;
    /**
     * E-mail
     */
    emaRes?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * Indicativo se o endereço é utilizado para entrega
     */
    indEnt?: boolean;
    indOba?: EnumIndOba;
    sitEnd?: EnumSitReg;
    /**
     * 
     */
    dthalt?: Date;
    e007ufs?: E007ufs;
    tipPes?: EnumJurFis;
    /**
     * 
     */
    usuger?: string;
    /**
     * Complemento
     */
    cplEnd?: string;
    /**
     * Nome do responsável
     */
    nomRes?: string;
    /**
     * Número
     */
    nenEnd?: string;
    /**
     * Bairro
     */
    baiEnd?: string;
    e008rai?: E008rai;
    e006pai?: E006pai;
    /**
     * Indicativo se o endereço é utilizado para cobrança
     */
    indCob?: boolean;
}
