/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E001pes } from './e001pes';
import { E007ufs } from './e007ufs';


export interface E001ine { 
    /**
     * 
     */
    usualt?: string;
    /**
     * 
     */
    dthger?: Date;
    e001pes?: E001pes;
    /**
     * Inscrição estadual
     */
    insEst?: string;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    e007ufs?: E007ufs;
    /**
     * 
     */
    usuger?: string;
}
