/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E006pai } from './e006pai';


export interface E007ufs { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * Nome
     */
    nomUfs?: string;
    /**
     * Sigla
     */
    sigUfs?: string;
    /**
     * 
     */
    dthger?: Date;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    e006pai?: E006pai;
    /**
     * 
     */
    usuger?: string;
}
