/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnumTipEmp } from './enumTipEmp';


export interface E026ram { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * Indicativo se o ramo de atividade trata-se de Armazém geral/Operador logístico
     */
    armGerOpeLog?: boolean;
    /**
     * 
     */
    dthger?: Date;
    /**
     * Descrição
     */
    desRam?: string;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * Ramo Atividade
     */
    codRam?: string;
    /**
     * Abreviatura
     */
    abrRam?: string;
    tipRam?: EnumTipEmp;
    /**
     * 
     */
    usuger?: string;
}
