/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.10.6
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface E030ban { 
    /**
     * Nome do banco
     */
    nomBan?: string;
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluido ?
     */
    excluido?: boolean;
    /**
     * 
     */
    dthger?: Date;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * Código
     */
    codBan?: string;
    /**
     * 
     */
    usuger?: string;
}
