/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.10.6
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E030ban } from './e030ban';


export interface E030age { 
    /**
     * Nome da agência
     */
    nomAge?: string;
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluido ?
     */
    excluido?: boolean;
    e030ban?: E030ban;
    /**
     * 
     */
    dthger?: Date;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * Código
     */
    codAge?: string;
    /**
     * 
     */
    usuger?: string;
}
