/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.10.6
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E001pes } from './e001pes';
import { E030age } from './e030age';
import { E030ban } from './e030ban';
import { EnumSitReg } from './enumSitReg';
import { EnumTipTcc } from './enumTipTcc';


export interface E077pes { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    e030ban?: E030ban;
    tipTcc?: EnumTipTcc;
    e030age?: E030age;
    /**
     * 
     */
    dthger?: Date;
    sitFav?: EnumSitReg;
    e001pes?: E001pes;
    /**
     * Número da conta corrente do favorecido no banco
     */
    ccbFav?: string;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    usuger?: string;
}
