/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { E001pes } from './e001pes';
import { E021mot } from './e021mot';
import { EnumSitReg } from './enumSitReg';
import { EnumTipAce } from './enumTipAce';
import { EnumTipEmc } from './enumTipEmc';


export interface E085pes { 
    /**
     * 
     */
    usualt?: string;
    /**
     * Indica se o registro foi excluído
     */
    excluido?: boolean;
    /**
     * 
     */
    dthger?: Date;
    tipAce?: EnumTipAce;
    e001pes?: E001pes;
    /**
     * Marca do cliente
     */
    marCli?: string;
    /**
     * 
     */
    dthalt?: Date;
    /**
     * Usuário responsável pelo motivo da situação do cliente
     */
    usuMot?: string;
    /**
     * Data do motivo da situação do cliente
     */
    dthMot?: Date;
    tipEmc?: EnumTipEmc;
    /**
     * 
     */
    usuger?: string;
    /**
     * Observação do motivo da situação do cliente
     */
    obsMot?: string;
    sitCli?: EnumSitReg;
    /**
     * 
     */
    id?: string;
    e021mot?: E021mot;
}
