/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.12.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumTipMer = 'VI' | 'VE';

export const EnumTipMer = {
    VI: 'VI' as EnumTipMer,
    VE: 'VE' as EnumTipMer
};
