/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumCifFob = 'V0' | 'V1' | 'V2' | 'V3' | 'V4' | 'V9';

export const EnumCifFob = {
    V0: 'V0' as EnumCifFob,
    V1: 'V1' as EnumCifFob,
    V2: 'V2' as EnumCifFob,
    V3: 'V3' as EnumCifFob,
    V4: 'V4' as EnumCifFob,
    V9: 'V9' as EnumCifFob
};
