/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumIndNif = 'V1' | 'V2' | 'V3';

export const EnumIndNif = {
    V1: 'V1' as EnumIndNif,
    V2: 'V2' as EnumIndNif,
    V3: 'V3' as EnumIndNif
};
