/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumFpgCom = 'VT' | 'VC' | 'VO';

export const EnumFpgCom = {
    VT: 'VT' as EnumFpgCom,
    VC: 'VC' as EnumFpgCom,
    VO: 'VO' as EnumFpgCom
};
