/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.12.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumTipAce = 'V1' | 'V2';

export const EnumTipAce = {
    V1: 'V1' as EnumTipAce,
    V2: 'V2' as EnumTipAce
};
