/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.10.6
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumTipEmc = 'V1' | 'V2';

export const EnumTipEmc = {
    V1: 'V1' as EnumTipEmc,
    V2: 'V2' as EnumTipEmc
};
