/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumTipTcc = 'V1' | 'V2' | 'V3' | 'V4' | 'V5' | 'V6' | 'V7' | 'V8' | 'V9' | 'V10';

export const EnumTipTcc = {
    V1: 'V1' as EnumTipTcc,
    V2: 'V2' as EnumTipTcc,
    V3: 'V3' as EnumTipTcc,
    V4: 'V4' as EnumTipTcc,
    V5: 'V5' as EnumTipTcc,
    V6: 'V6' as EnumTipTcc,
    V7: 'V7' as EnumTipTcc,
    V8: 'V8' as EnumTipTcc,
    V9: 'V9' as EnumTipTcc,
    V10: 'V10' as EnumTipTcc
};
