/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumIndOba = 'V0' | 'V1' | 'V2';

export const EnumIndOba = {
    V0: 'V0' as EnumIndOba,
    V1: 'V1' as EnumIndOba,
    V2: 'V2' as EnumIndOba
};
