/**
 * Pessoa
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumIndFor = 'VM' | 'VP' | 'VA';

export const EnumIndFor = {
    VM: 'VM' as EnumIndFor,
    VP: 'VP' as EnumIndFor,
    VA: 'VA' as EnumIndFor
};
