/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.10.6
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumZonFra = 'V0' | 'V1' | 'V2' | 'V3' | 'V4';

export const EnumZonFra = {
    V0: 'V0' as EnumZonFra,
    V1: 'V1' as EnumZonFra,
    V2: 'V2' as EnumZonFra,
    V3: 'V3' as EnumZonFra,
    V4: 'V4' as EnumZonFra
};
