/**
 * Pessoa
 * Serviço de Gestão de Pessoas do ERPX
 *
 * OpenAPI spec version: 1.12.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type EnumAplMot = 'V1' | 'V2' | 'V3' | 'V4' | 'V5' | 'V6' | 'V8' | 'V9' | 'V11' | 'V12' | 'V13' | 'V14' | 'V20' | 'V36' | 'V40' | 'V42' | 'V43' | 'V44' | 'V45' | 'V46' | 'V49' | 'V51' | 'V52' | 'V99';

export const EnumAplMot = {
    V1: 'V1' as EnumAplMot,
    V2: 'V2' as EnumAplMot,
    V3: 'V3' as EnumAplMot,
    V4: 'V4' as EnumAplMot,
    V5: 'V5' as EnumAplMot,
    V6: 'V6' as EnumAplMot,
    V8: 'V8' as EnumAplMot,
    V9: 'V9' as EnumAplMot,
    V11: 'V11' as EnumAplMot,
    V12: 'V12' as EnumAplMot,
    V13: 'V13' as EnumAplMot,
    V14: 'V14' as EnumAplMot,
    V20: 'V20' as EnumAplMot,
    V36: 'V36' as EnumAplMot,
    V40: 'V40' as EnumAplMot,
    V42: 'V42' as EnumAplMot,
    V43: 'V43' as EnumAplMot,
    V44: 'V44' as EnumAplMot,
    V45: 'V45' as EnumAplMot,
    V46: 'V46' as EnumAplMot,
    V49: 'V49' as EnumAplMot,
    V51: 'V51' as EnumAplMot,
    V52: 'V52' as EnumAplMot,
    V99: 'V99' as EnumAplMot
};
